config/routes.rb
MyPortfolio::Application.routes.draw do

  devise_for :users,
             controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :posts do
    resources :comments
  end
  resources :projects do
    resources :comments
  end

  root to: 'static_pages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :approved, :author, :author_email, :author_url,
                   :content, :referrer, :user_agent, :user_ip, :post_id,
                   :commentable_id, :commentable, :comment

  belongs_to :commentable, polymorphic: true
  validates :content,      presence: true
  validates :author_email, presence: true
  validates :author,       presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  attr_accessible :title, :body, :published
  scope :published, where(published: true)
  def publish!
    published = true
    save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :technologies_used, :image

  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :name, :password_confirmation, :remember_me, :role, :published
  # attr_accessible :title, :body
  has_many :posts, foreign_key: "author_id"

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_commentable

  def create
    @comment = @commentable.comments.new(params[:comment])
    if @comment.save
      flash[:notice] = "Comment is awaiting moderation"
      redirect_to @commentable
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @commentable = @comment.commentable
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to @commentable, notice: "Comment deleted."}
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @commentable = @comment.commentable
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @commentable, notice: 'comment has been approved.' }
        format.json { head :no_content }
      else
        instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
        render template: "#{@resource}/show"
      end
    end
  end


private

  def load_commentable
    @resource, id = request.path.split('/')[1,2]
    @commentable = @resource.singularize.classify.constantize.find(id)
    #same as post/project.find(id)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.name}, you are signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = policy_scope(Post)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
     @post = Post.find(params[:id])
     authorize @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    authorize @post
    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url notice: "Post was deleted." }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      respond_to do |format|
        format.html {  redirect_to @project  }
        format.js
      end
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      respond_to do |format|
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 # translate the rails flash levels to appropriate twitter bootstrap css classes
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_comment.html.erb
<div class="comment_form">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [@commentable, @comment] do |f| %>
    <div class="field">
      <%= f.label :author, "Your name" %><br />
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :author_email, "Your email"%><br>
      <%= f.text_field :author_email %><br>
    </div>
    <div class="field">
      <%= f.label :author_url, "Your URL" %><br />
      <%= f.text_field :author_url %>
    </div>
    <div class="field">
      <%= f.label :content, "Your Comment"%><br>
      <%= f.text_area :content %>
    </div>
     <%= f.hidden_field :referrer, value: request.referrer %>
      <%= f.hidden_field :commentable_id,  value: @commentable.id %>
    <div class="actions">
      <%= f.submit "Submit comment for approval" %>
    </div>
  <% end %>
</div>

app/views/layouts/_commentshow.html.erb
<h3> Comments: </h3>
<% @commentable.comments.each do |comment| %>
  <table>
    <% if comment.approved? || (current_user &&current_user.editor?) %>
      <tr>
        <td>By: <%= comment.author %></td>
      </tr>
      <tr>
        <td>Email: <%= comment.author_email %></td>
      </tr>
      <tr>
        <td>Content: <%= comment.content %></td>
      </tr>
    <% end %>
    <% if current_user && current_user.editor? %>
      <tr>
        <td><%= button_to 'Delete', polymorphic_path([@commentable, comment]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% unless comment.approved? %>
          <td><%= button_to 'Approve', polymorphic_path([@commentable, comment], comment: {approved: true}), method: :put %> </td>
        <% end %>
      <tr>
    <% end %>
  </table><br>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="fixed-nav">
  <div class="left" id="signature">
     <%= link_to image_tag("me.jpg", alt: "me", id: "my-pic"), "http://dreb.herokuapp.com" %>
  </div>
  <div class="middle">
    <div id="headline">
      <div id="tag">
        I'm Andre, a Rails developer
      </div>
    </div>
    <div id="nav-buttons">
      <%= link_to "Blog", posts_path, id:"blog" %>
      <%= link_to "Projects", projects_path, id: "projects" %>
    </div>
  </div>
  <div class="right">
    <ul class="social">
      <li>
        <%=image_tag("github.png", alt: "github", class:"soc-icon")%>
        <a href="http://github.com/andrebautista">Github</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andre's Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
   <% if policy(Post).publish? %>
    <div class="field">
      <%= f.label :published %>
      <%= f.check_box :published %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr id="<%= dom_id(post) %>">
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <% if policy(post).update? %>
       <td>
        <%= link_to 'Edit', edit_post_path(post) %>
        <span><%= "Published" if post.published %></span>
      </td>
    <% end %>
    <% if policy(post).destroy? %>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p id="author">
  <b>By:</b>
  <%= @post.author.email %>
</p>


<% if policy(@post).destroy? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

<%= render "layouts/commentshow" %>
<%= render "layouts/comment" %>

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h4>Project could not be saved</h4>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', projects_path, id:'back_link', remote: true %>

app/views/projects/_project.html.erb
<div class="project" id="<%= dom_id(project) %>">
  <h3><%= project.name %></h3>
  <p><%= project.technologies_used %></p>
  <%= image_tag project.image_url.to_s %>
  <div class="nav">
    <%= link_to 'Show', project %> |
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, id: 'delete_project_link', remote: true %> |
    <%= link_to 'Edit', edit_project_path(project), id: "edit_project_link_#{project.id}", remote: true %>
  </div>
</div>

app/views/projects/create.js.erb
$('#new_project').remove();
$('#create_project_link').show();
$('.project:last').after('<%= j render(@project) %>');
$("<%= "#edit_project_link_#{@project.id}" %>").show();
$("#back_link").remove();

app/views/projects/destroy.js.erb
$("#<%= "project_#{@project.id}" %>").remove();

app/views/projects/edit.html.erb
<%= render "form" %>

<%= link_to 'Back', projects_path, id:'back_link' %>

app/views/projects/edit.js.erb
$("<%= "#edit_project_link_#{@project.id}" %>").closest('.project').append('<%= j render("form") %>');
$("<%= "#edit_project_link_#{@project.id}" %>").hide();
$("#back_link").on("click", function()  {
  $('#edit_project_<%= @project.id %>').remove();
  $("#back_link").remove();
  $("<%= "#edit_project_link_#{@project.id}" %>").show();
});

app/views/projects/index.html.erb
<%= render @projects %>

<br />
<%= link_to 'New project' ,new_project_path, id: 'create_project_link', remote: true %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form" %>
<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#create_project_link').hide().after('<%= j render("form") %>');
$("#back_link").on("click", function()  {
  $('#new_project').remove();
  $("#back_link").remove();
  $('#create_project_link').show();
});

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%= @project.technologies_used %>
<%= render 'layouts/commentshow' %>
<%= render 'layouts/comment' %>

app/views/projects/update.js.erb
$("#<%= "project_#{@project.id}" %>").replaceWith('<%= j render(@project) %>');
$("#edit_project_<%= @project.id %>").remove();
$("#back_link").remove();